// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB0hAoGpzCgdNEDuNTv8grDOjTecjufSI',
    appId: '1:138903380012:web:84140407a7a2226ced3189',
    messagingSenderId: '138903380012',
    projectId: 'mobile-project-d3604',
    authDomain: 'mobile-project-d3604.firebaseapp.com',
    storageBucket: 'mobile-project-d3604.appspot.com',
    measurementId: 'G-T7QD2YJCG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-YmtcnpKzOHsg9tUA-rL1GDw-QpdDuvw',
    appId: '1:138903380012:android:a4521335d1f8eec2ed3189',
    messagingSenderId: '138903380012',
    projectId: 'mobile-project-d3604',
    storageBucket: 'mobile-project-d3604.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP6Wq58J1UAWb-HdqCjfiDOautS4PKmOI',
    appId: '1:138903380012:ios:ac682bc42e9311e8ed3189',
    messagingSenderId: '138903380012',
    projectId: 'mobile-project-d3604',
    storageBucket: 'mobile-project-d3604.appspot.com',
    iosClientId: '138903380012-ql0ir073kvdonmr2eddkl8v31iqsbtiu.apps.googleusercontent.com',
    iosBundleId: 'com.sekolah.dataSiswa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP6Wq58J1UAWb-HdqCjfiDOautS4PKmOI',
    appId: '1:138903380012:ios:3b8258cc27f56430ed3189',
    messagingSenderId: '138903380012',
    projectId: 'mobile-project-d3604',
    storageBucket: 'mobile-project-d3604.appspot.com',
    iosClientId: '138903380012-mb2gk4b3homud27suvcbprs8tm1tne0h.apps.googleusercontent.com',
    iosBundleId: 'com.sekolah.dataSiswa.RunnerTests',
  );
}
